# Generated by Django 5.0.4 on 2024-05-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(max_length=255)),
                ('token_contract_address', models.CharField(max_length=255)),
                ('token_image', models.ImageField(upload_to='tokenImages')),
                ('token_decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_buy_listing_fee', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('offer_sell_listing_fee', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('selling_fee', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=256)),
                ('token_address', models.CharField(max_length=256)),
                ('amount_of_token', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=1024)),
                ('fill_type', models.CharField(choices=[('PARTIAL_FILL', 'PARTIAL_FILL'), ('FULL_FILL', 'FULL_FILL')], max_length=255)),
                ('offer_type', models.CharField(choices=[('BUYING', 'BUYING'), ('SELLING', 'SELLING')], max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCapi.wallet')),
            ],
        ),
    ]
