# Generated by Django 5.0.4 on 2024-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTCapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restricttoken',
            old_name='token_contract_address',
            new_name='token_address',
        ),
        migrations.AlterField(
            model_name='tokenoffering',
            name='token_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenoffering',
            name='token_name',
            field=models.CharField(max_length=255),
        ),
    ]
